# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/liuyx/work/learn/inline-hook/inline-hook

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/liuyx/work/learn/inline-hook/inline-hook

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/liuyx/work/learn/inline-hook/inline-hook/CMakeFiles /home/liuyx/work/learn/inline-hook/inline-hook/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/liuyx/work/learn/inline-hook/inline-hook/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hooker-test

# Build rule for target.
hooker-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hooker-test
.PHONY : hooker-test

# fast build rule for target.
hooker-test/fast:
	$(MAKE) -f CMakeFiles/hooker-test.dir/build.make CMakeFiles/hooker-test.dir/build
.PHONY : hooker-test/fast

Hooker.o: Hooker.cpp.o
.PHONY : Hooker.o

# target to build an object file
Hooker.cpp.o:
	$(MAKE) -f CMakeFiles/hooker-test.dir/build.make CMakeFiles/hooker-test.dir/Hooker.cpp.o
.PHONY : Hooker.cpp.o

Hooker.i: Hooker.cpp.i
.PHONY : Hooker.i

# target to preprocess a source file
Hooker.cpp.i:
	$(MAKE) -f CMakeFiles/hooker-test.dir/build.make CMakeFiles/hooker-test.dir/Hooker.cpp.i
.PHONY : Hooker.cpp.i

Hooker.s: Hooker.cpp.s
.PHONY : Hooker.s

# target to generate assembly for a file
Hooker.cpp.s:
	$(MAKE) -f CMakeFiles/hooker-test.dir/build.make CMakeFiles/hooker-test.dir/Hooker.cpp.s
.PHONY : Hooker.cpp.s

HookerArm.o: HookerArm.cpp.o
.PHONY : HookerArm.o

# target to build an object file
HookerArm.cpp.o:
	$(MAKE) -f CMakeFiles/hooker-test.dir/build.make CMakeFiles/hooker-test.dir/HookerArm.cpp.o
.PHONY : HookerArm.cpp.o

HookerArm.i: HookerArm.cpp.i
.PHONY : HookerArm.i

# target to preprocess a source file
HookerArm.cpp.i:
	$(MAKE) -f CMakeFiles/hooker-test.dir/build.make CMakeFiles/hooker-test.dir/HookerArm.cpp.i
.PHONY : HookerArm.cpp.i

HookerArm.s: HookerArm.cpp.s
.PHONY : HookerArm.s

# target to generate assembly for a file
HookerArm.cpp.s:
	$(MAKE) -f CMakeFiles/hooker-test.dir/build.make CMakeFiles/hooker-test.dir/HookerArm.cpp.s
.PHONY : HookerArm.cpp.s

HookerFactory.o: HookerFactory.cpp.o
.PHONY : HookerFactory.o

# target to build an object file
HookerFactory.cpp.o:
	$(MAKE) -f CMakeFiles/hooker-test.dir/build.make CMakeFiles/hooker-test.dir/HookerFactory.cpp.o
.PHONY : HookerFactory.cpp.o

HookerFactory.i: HookerFactory.cpp.i
.PHONY : HookerFactory.i

# target to preprocess a source file
HookerFactory.cpp.i:
	$(MAKE) -f CMakeFiles/hooker-test.dir/build.make CMakeFiles/hooker-test.dir/HookerFactory.cpp.i
.PHONY : HookerFactory.cpp.i

HookerFactory.s: HookerFactory.cpp.s
.PHONY : HookerFactory.s

# target to generate assembly for a file
HookerFactory.cpp.s:
	$(MAKE) -f CMakeFiles/hooker-test.dir/build.make CMakeFiles/hooker-test.dir/HookerFactory.cpp.s
.PHONY : HookerFactory.cpp.s

HookerThumb.o: HookerThumb.cpp.o
.PHONY : HookerThumb.o

# target to build an object file
HookerThumb.cpp.o:
	$(MAKE) -f CMakeFiles/hooker-test.dir/build.make CMakeFiles/hooker-test.dir/HookerThumb.cpp.o
.PHONY : HookerThumb.cpp.o

HookerThumb.i: HookerThumb.cpp.i
.PHONY : HookerThumb.i

# target to preprocess a source file
HookerThumb.cpp.i:
	$(MAKE) -f CMakeFiles/hooker-test.dir/build.make CMakeFiles/hooker-test.dir/HookerThumb.cpp.i
.PHONY : HookerThumb.cpp.i

HookerThumb.s: HookerThumb.cpp.s
.PHONY : HookerThumb.s

# target to generate assembly for a file
HookerThumb.cpp.s:
	$(MAKE) -f CMakeFiles/hooker-test.dir/build.make CMakeFiles/hooker-test.dir/HookerThumb.cpp.s
.PHONY : HookerThumb.cpp.s

HookerX64.o: HookerX64.cpp.o
.PHONY : HookerX64.o

# target to build an object file
HookerX64.cpp.o:
	$(MAKE) -f CMakeFiles/hooker-test.dir/build.make CMakeFiles/hooker-test.dir/HookerX64.cpp.o
.PHONY : HookerX64.cpp.o

HookerX64.i: HookerX64.cpp.i
.PHONY : HookerX64.i

# target to preprocess a source file
HookerX64.cpp.i:
	$(MAKE) -f CMakeFiles/hooker-test.dir/build.make CMakeFiles/hooker-test.dir/HookerX64.cpp.i
.PHONY : HookerX64.cpp.i

HookerX64.s: HookerX64.cpp.s
.PHONY : HookerX64.s

# target to generate assembly for a file
HookerX64.cpp.s:
	$(MAKE) -f CMakeFiles/hooker-test.dir/build.make CMakeFiles/hooker-test.dir/HookerX64.cpp.s
.PHONY : HookerX64.cpp.s

HookerX86.o: HookerX86.cpp.o
.PHONY : HookerX86.o

# target to build an object file
HookerX86.cpp.o:
	$(MAKE) -f CMakeFiles/hooker-test.dir/build.make CMakeFiles/hooker-test.dir/HookerX86.cpp.o
.PHONY : HookerX86.cpp.o

HookerX86.i: HookerX86.cpp.i
.PHONY : HookerX86.i

# target to preprocess a source file
HookerX86.cpp.i:
	$(MAKE) -f CMakeFiles/hooker-test.dir/build.make CMakeFiles/hooker-test.dir/HookerX86.cpp.i
.PHONY : HookerX86.cpp.i

HookerX86.s: HookerX86.cpp.s
.PHONY : HookerX86.s

# target to generate assembly for a file
HookerX86.cpp.s:
	$(MAKE) -f CMakeFiles/hooker-test.dir/build.make CMakeFiles/hooker-test.dir/HookerX86.cpp.s
.PHONY : HookerX86.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/hooker-test.dir/build.make CMakeFiles/hooker-test.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/hooker-test.dir/build.make CMakeFiles/hooker-test.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/hooker-test.dir/build.make CMakeFiles/hooker-test.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... hooker-test"
	@echo "... rebuild_cache"
	@echo "... Hooker.o"
	@echo "... Hooker.i"
	@echo "... Hooker.s"
	@echo "... HookerArm.o"
	@echo "... HookerArm.i"
	@echo "... HookerArm.s"
	@echo "... HookerFactory.o"
	@echo "... HookerFactory.i"
	@echo "... HookerFactory.s"
	@echo "... HookerThumb.o"
	@echo "... HookerThumb.i"
	@echo "... HookerThumb.s"
	@echo "... HookerX64.o"
	@echo "... HookerX64.i"
	@echo "... HookerX64.s"
	@echo "... HookerX86.o"
	@echo "... HookerX86.i"
	@echo "... HookerX86.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

